Parameters:
  DBName: 
    Type: String
  DBUsername: 
    Type: String
  DBPassword: 
    Type: String
    NoEcho: true
  Subnet1Id: 
    Type: String
  Subnet2Id: 
    Type: String
  VPCId: 
    Type: String

Outputs:
  Endpoint:
    Value: !GetAtt DBInstance.Endpoint.Address

Resources:
  DBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "rds"
      GroupDescription: "Security group for RDS"
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "3306"
          ToPort: "3306"
          CidrIp: "0.0.0.0/0"
      SecurityGroupEgress:
        - IpProtocol: "-1"
          FromPort: "0"
          ToPort: "0"
          CidrIp: "0.0.0.0/0"

  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'Example DB subnet group'
      SubnetIds:
        - !Ref Subnet1Id
        - !Ref Subnet2Id

  DBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: !Ref DBName
      DBInstanceIdentifier: 'wordpress-db-instance'
      Engine: 'mariadb'
      EngineVersion: '10.6.10'
      DBInstanceClass: 'db.t2.micro'
      AllocatedStorage: 20
      StorageType: 'gp2'
      PubliclyAccessible: false
      MultiAZ: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
    DeletionPolicy: "Delete"
