spec_version: 2
description: ADOC original blueprint.

# blueprint inputs can be provided by the user, API or CI plugin when creating an environment from this blueprint.
inputs:
  region:
    type: string
    default: ap-northeast-1
  route_table_id:
    type: string
    default: rtb-00000000000000000
  destination_cidr_block:
    type: string
    default: 0.0.0.0/0
  gateway_id:
    type: string
  execution_host:
    type: execution-host

# blueprint outputs define which data that was generated during environment provisioning will be returned to the user, API or CI.
outputs:
  route_id:
    value: '{{ .grains.aws-route.outputs.route_id }}'

grains:
  aws-route:
    kind: terraform
    spec:
      source:
        store: torque-bps
        path: assets/aws-route
      host:
      # Execution Host - the platform where the asset executable will run.
      # For example, a Kubernetes cluster can be used as an execution host.
        name: '{{ .inputs.execution_host }}'
        # A service account annotated with a role ARN with permissions to run the asset
        # service-account: <service-account-name>
      inputs:
      - route_table_id: '{{ .inputs.route_table_id }}'
      # - destination_cidr_block: '{{ .inputs.destination_cidr_block }}'
      - destination_cidr_block: '0.0.0.0/0'
      - gateway_id: '{{ .inputs.gateway_id }}'
      - region: '{{ .inputs.region }}'
      # The environment variables declared in this section will be available during the grain deployment as well as the grain destroy phase
      # env-vars:
      # - VAR_NAME: var value
      env-vars: []
      outputs:
      - route_id
    # The terraform version that will be used to deploy the module
    tf-version: 1.3.6
